package net.octopvp.octocore.common.object.redis;

public enum JedisAction {
    DISCORD_STAFF_CHAT, STAFF_ALERT, ADMIN_ALERT,
    AUDIT_LOG,
    GLOBAL_BROADCAST,
    RESPONSE,

    PERMISSIONS_UPDATE, RANKS_UPDATE,

    RELOAD_TAGS, TAG_UPDATE,
    PDATA_UPDATE,

    EXECUTE_PUNISHMENT, EXECUTE_UNBLACKLIST, EXECUTE_UNMUTE, EXECUTE_UNBAN, EXECUTE_ALT_KICK,

    SAVE_REQUEST_SWITCH,
    SAVE_REQUEST_MISC,

    PUNISHED_JOIN
}
