package net.octopvp.octocore.common.object.redis;

public enum JedisAction {
    SERVER_DATA, PLAYER_DATA, PLAYER_MESSAGE, REPORT_SAVE,
    SERVER_COMMAND, GRANTS_UPDATE,
    SERVER_ONLINE, SERVER_OFFLINE, GLOBAL_COMMAND,
    STAFF_CHAT, STAFF_CONNECT, STAFF_SWITCH, STAFF_DISCONNECT,
    ADMIN_CHAT,
    DISCORD_ADMIN_CHAT, DISCORD_STAFF_CHAT, STAFF_ALERT, ADMIN_ALERT,
    SEND_DISCORD_MESSAGE, AUDIT_LOG,
    GLOBAL_BROADCAST,
    RESPONSE,

    PERMISSIONS_UPDATE, RANKS_UPDATE,

    RELOAD_TAGS, TAG_UPDATE, RELOAD_RANKS,
    PDATA_UPDATE,

    EXECUTE_PUNISHMENT, EXECUTE_UNBLACKLIST, EXECUTE_UNMUTE, EXECUTE_UNBAN, EXECUTE_ALT_KICK,

    SAVE_REQUEST_SWITCH,
    SAVE_REQUEST_MISC,

    PUNISHED_JOIN
}
