package net.octopvp.octocore.common.object.redis;

public enum JedisAction {
    SERVER_DATA, PLAYER_DATA, PLAYER_MESSAGE, REPORT_SAVE,
    EXECUTE_PUNISHMENT
    , SERVER_COMMAND, GRANTS_UPDATE,
    SERVER_ONLINE, SERVER_OFFLINE, GLOBAL_COMMAND,
    UPDATE_SQL_FILTER_DB,UPDATE_SQL_DISABLED_COMMANDS_DB,
    STAFF_CHAT,STAFF_CONNECT, STAFF_SWITCH, STAFF_DISCONNECT,
    ADMIN_CHAT,
    DISCORD_ADMIN_CHAT,DISCORD_STAFF_CHAT,STAFF_ALERT,ADMIN_ALERT,
    SEND_DISCORD_MESSAGE,AUDIT_LOG,
    GLOBAL_BROADCAST,
    RESPONSE,

    PERMISSIONS_UPDATE,RANKS_UPDATE,

    RELOAD_TAGS,RELOAD_RANKS,
    PDATA_UPDATE,

    SAVE_REQUEST_SWITCH
    ;
}
