database:
  sql:
    username: octocore
    password: octocore
    db: octocore
    url: localhost
    port: 3306
  redis:
    host: localhost
    port: 6379
    password: 'default'
tab:
  header: '&a&lPlaying on the OctoPvP Network&r'
  footer: '&e&lplay.octopvp.net'
update-tab-interval: 45
update-pdata-interval: 100