#The master server on the network (can only be 1)
server-type: MASTER
master:
  discord:
    enabled: true
    token: '-'
    channels:
      master-ctrl-status: '834815775046500419'
      audit: '835393497669828608'
  tebex:
    api-key: ''

name: lobby
server-ip: beta.octopvp.net
database:
  sql:
    username: octocore
    password: octocore
    db: octocore
    url: localhost
    port: 3306
  redis:
    enabled: false
    host: localhost
    port: 6379
    auth:
      enabled: false
      username: default
      password: default
  mongo:
    host: localhost
    port: 27017
    auth:
      enabled: false
      username: default
      password: default
      db: default
tab:
  header: '&b&lOctoPvP&r\n'
  footer: '\n&aOctoPvP.net\n'
update-tab-interval: 45
update-pdata-interval: 100
default-tab: true
health-display: true
build-prot: true
sentry:
  enable: true
  sentry-dsn: 'https://94dee64522e045f8bfa38796e9b130b6@o1085901.ingest.sentry.io/6097374'
punish:
  alts:
    max: 5
    #allow alts on this server
    allow-alts: true
settings:
  auto-respawn: true
  world-name: world
  spawn:
    x: 0
    y: 100
    z: 0
