name: OctoRPG
version: 0.0.1
main: net.octopvp.octocore.rpg.OctoRPG
bootstrapper: net.octopvp.octocore.rpg.OctoRPGBootstrap
api-version: '1.21'
authors: [Pylons]
description: rpg plugin for OctoCore
dependencies:
  server:
    OctoCore:
      load: BEFORE
      required: true
    DecentHolograms:
      load: BEFORE
      required: true
    ProtocolLib:
      load: BEFORE
      required: true
    Citizens:
      load: BEFORE
      required: true
permissions:
  octorpg.item.weapons:
    default: false
  octorpg.item.armour:
    default: false
  octorpg.item.tools:
    default: false
  octorpg.item.blocks:
    default: false
  octorpg.item.food:
    default: false
  octorpg.item.all:
    default: false
  octorpg.item.custom:
    default: false
  octorpg.item.search:
    default: false
  octorpg.blacklist.bypass:
    default: false
