saml.sp-entity-id=AetheriaCore-Master-DEV

master.redis.hostname=140.238.153.142
master.redis.port=6379
master.redis.password=PVuS9YfX43

spring.data.mongodb.database=AetheriaCore
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.username=admin
spring.data.mongodb.password=admin
spring.data.mongodb.authentication-database=admin

dev=true
