# App Properties
spring:
  security:
    saml2:
      relyingparty:
        registration:
          octoauth:
            singlelogout:
              binding: POST
              url: "https://auth.octomc.net/application/saml/octocore-test/slo/binding/post/"
            assertingparty:
              singlesignon:
                url: "https://auth.octomc.net/application/saml/octocore-test/sso/binding/redirect/"
                binding: REDIRECT
              metadata-uri: "https://auth.octomc.net/api/v3/providers/saml/11/metadata/?download"
  gson:
    pretty-printing: true
  data:
    mongodb:
      database: 'OctoCore'
      host: 'localhost'
      port: 27017
  mvc:
    converters:
      preferred-json-mapper: 'gson'
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
auth:
  secret: jsdogh298gh92uihuiheg29jfewiohg2
  expiration: 86400000 # 1 day
  cookieName: 'auth'
vaadin:
  pnpm-enabled: true
master:
  redis:
    hostname: 140.238.153.142
    port: 6379
    password: PVuS9YfX43
  mongo:
    database: 'OctoCore'
    host: 'localhost'
    port: 27017
    auth:
      enabled: false
      user: ''
      password: ''
      db: 'admin'
