logging.level.org.springframework.security.saml=INFO
logging.level.org.opensaml=INFO
logging.level.com.vdenotaris.spring.boot.security.saml=INFO
#logging.file.name=logs/file.log
spring.main.allow-circular-references=TRUE

saml.meta-url=https://hub.aetheria.world/hub/api/rest/saml2/metadata
saml.sp-entity-id=AetheriaCore-Master
saml.sp-private-key-password=whhGDPy2O7Bf*c4lGh#
saml.sp-alias=Hub_SAML
saml.sp-private-key-file=classpath:/saml/samlKeystore.jks
saml.attribute.email=mail
saml.attribute.username=uid
saml.attribute.fullname=displayName
saml.attribute.groups=member-of

server.forward-headers-strategy=framework
server.servlet.session.cookie.http-only=false

master.redis.hostname=140.238.147.43
master.redis.port=6379
master.redis.password=qCmA4RMH3NYZv7N

spring.data.mongodb.database=AetheriaCore
spring.data.mongodb.host=140.238.147.43
spring.data.mongodb.port=27017
spring.data.mongodb.username=aetheria
spring.data.mongodb.password=8WzYBd9q2UhKxx4
spring.data.mongodb.authentication-database=admin

jetbrains.hub.url=https://hub.aetheria.world/


dev=false
