# App Properties
spring:
  gson:
    pretty-printing: true
  data:
    mongodb:
      database: 'OctoCore'
      host: 'localhost'
      port: 27017
  mvc:
    converters:
      preferred-json-mapper: 'gson'
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
auth:
  secret: jsdogh298gh92uihuiheg29jfewiohg2
  expiration: 86400000 # 1 day
  cookieName: 'auth'
vaadin:
  pnpm-enabled: true
server:
  max-http-header-size: 100MB
jetbrains:
  hub:
    url: https://hub.octopvp.net/hub

master:
  redis:
    hostname: 140.238.153.142
    port: 6379
    password: PVuS9YfX43
saml2:
  identity-provider:
    base-path: https://master.octopvp.net/saml/idp
    entity-id: octocore-idp
    #sign-metadata: true
    #sign-assertions: true # not working on java 17, only works on java 8 for some reason
    #encrypt-assertions: false
    #want-requests-signed: true
    #signing-algorithm: RSA_SHA256
    digest-method: SHA256
    #single-logout-enabled: true
    name-ids:
      - urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
      - urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
      - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
    keys:
      active:
        name: active-idp-key
        private-key: ./keys/privkey.pem
        certificate: ./keys/cacert.pem
        passphrase: password
