package net.octopvp.octocore.paper.database.redis.object;

public enum JedisAction {
    SERVER_DATA, PLAYER_DATA, PLAYER_MESSAGE, REPORT_SAVE,
    /**
     * Should be run on master server only (litebans) until we replace litebans
     */
    EXECUTE_PUNISHMENT
    , SERVER_COMMAND, GRANTS_UPDATE,
    SERVER_ONLINE, SERVER_OFFLINE, GLOBAL_COMMAND,
    UPDATE_SQL_FILTER_DB,UPDATE_SQL_DISABLED_COMMANDS_DB,
    STAFF_CHAT,STAFF_CONNECT, STAFF_SWITCH, STAFF_DISCONNECT,
    ADMIN_CHAT,
    DISCORD_ADMIN_CHAT,DISCORD_STAFF_CHAT,STAFF_ALERT,ADMIN_ALERT,
    SEND_DISCORD_MESSAGE,AUDIT_LOG,
    GLOBAL_BROADCAST,
    RESPONSE,

    RELOAD_TAGS,
    PDATA_UPDATE
    ;
}
