server-type: HUB
name: lobby
server-ip: play.octomc.net
database:
  redis:
    enabled: false
    host: localhost
    port: 6379
    auth:
      enabled: false
      username: default
      password: default
  mongo:
    host: localhost
    port: 27017
    auth:
      enabled: false
      username: default
      password: default
      db: default
tab:
  header: '&b&lOctoMC&r\n'
  footer: '\n&aOctoMC.net\n'
update-tab-interval: 45
update-pdata-interval: 100
default-tab: true
health-display: true
build-prot: true
sentry:
  enable: true
  sentry-dsn: 'https://94dee64522e045f8bfa38796e9b130b6@o1085901.ingest.sentry.io/6097374'
punish:
  alts:
    max: 5
    #allow alts on this server
    allow-alts: true
settings:
  auto-respawn: true
  world-name: world
  spawn:
    x: 0
    y: 100
    z: 0
master-url: 'https://master.octopvp.net/'
