/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://m2.dv8tion.net/releases")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.dmulloy2.net/repository/public/")
    }

    maven {
        url = uri("https://maven.moonsworth.com/repository/lunarclient-public/")
    }

    maven {
        url = uri("https://repo.citizensnpcs.co/")
    }

    maven {
        url = uri("http://ci.nametagedit.com/plugin/repository/everything/")
        isAllowInsecureProtocol = true
    }

    maven {
        url = uri("https://repo.viaversion.com")
    }
}

dependencies {
    implementation("org.slf4j:slf4j-log4j12:1.7.5")
    implementation("org.mongodb:mongodb-driver-sync:4.2.2")
    implementation("redis.clients:jedis:2.9.0")
    implementation("org.apache.commons:commons-compress:1.21")
    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("net.badbird5907:JDACommand:2.0.0-REL")
    implementation("club.minnced:discord-webhooks:0.5.7")
    implementation("org.javatuples:javatuples:1.2")
    implementation("io.sentry:sentry:5.6.0")
    implementation("com.google.guava:guava:31.1-jre")
    compileOnly("org.projectlombok:lombok:1.18.22")
}

group = "net.octopvp"
version = "1.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
