name: OctoCore
version: ${project.version}
main: net.octopvp.octocore.v1_19.Bootstrap1_19
api-version: 1.19
authors: [ Badbird5907 ]
description: OctoCore
load: STARTUP
depend:
  - ProtocolLib
  - LunarClient-API
  - Citizens
softdepend:
  - Vault
