<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>OctoCore</artifactId>
        <groupId>net.octopvp</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>OctoCore-build</artifactId>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>net.octopvp</groupId>
            <artifactId>OctoCore-paper</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>net.octopvp</groupId>
            <artifactId>OctoCore-waterfall</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>net.octopvp</groupId>
            <artifactId>OctoCore-common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <defaultGoal>clean package</defaultGoal>
        <directory>../target</directory>
        <finalName>OctoCore</finalName>
        <resources>
            <resource>
                <targetPath>.</targetPath>
                <filtering>true</filtering>
                <directory>../OctoCore-paper/src/main/resources</directory>
                <includes>
                    <include>**/*.yml</include>
                </includes>
            </resource>
            <resource>
                <targetPath>.</targetPath>
                <filtering>true</filtering>
                <directory>../OctoCore-waterfall/src/main/resources</directory>
                <includes>
                    <include>**/*.yml</include>
                </includes>
            </resource>
            <resource>
                <targetPath>.</targetPath>
                <filtering>true</filtering>
                <directory>../OctoCore-common/src/main/resources</directory>
                <includes>
                    <include>**/*.yml</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.3.1</version>
                <configuration>
                    <outputDirectory>C:\Users\evanl\OctoPvP\Network\lobby\plugins</outputDirectory>
                    <archive>
                        <index>true</index>
                        <manifestEntries>
                            <Built-By>OctoDev</Built-By>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                            </artifactSet>
                            <relocations>
                                <relocation>
                                    <pattern>club.minnced</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.discord</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>dev.samstevens</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.totp</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>net.dv8tion.jda</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.jda</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.mongodb</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.mongo</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.fasterxml.jackson</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.jackson</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>redis.clients</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.redis</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>io.sentry</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.sentry</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>gnu.trove</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.trove</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.intellij</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.jetbrains</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>jetbrains</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.jetbrains</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.commons.lang3</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.apache</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.commons.compress</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.apache</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.commons.collections4</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.apache</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.commons.logging</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.apache</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.commons.pool2</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.apache</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.commons.codec</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.apache</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.http</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.apache</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.log4j</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.apache</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.github.jaiimageio</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.jaiimageio</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.neovisionaries</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.neovidionaries</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.beust</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.beust</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.iwebpp</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.iwebpp</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.zxing</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.zxing</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>okhttp3</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.okhttp3</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>okio</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.okio</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>oshi</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.oshi</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>tomp2p</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.opus</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.bson</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.bson</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.javatuples</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.javatuples</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.json</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.json</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.reflections</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.reflections</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.slf4j</pattern>
                                    <shadedPattern>net.octopvp.octocore.shade.slf4j</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
