name: OctoCore
version: ${project.version}
main: net.octopvp.octocore.v1_21.Bootstrap1_21
api-version: "1.21"
authors: [ Badbird5907 ]
description: OctoCore
load: STARTUP
depend:
  - ProtocolLib
  - Citizens
softdepend:
  - Vault
